version: '3.8'
services:
    esdatacheck:
        image: 'registry.cn-hangzhou.aliyuncs.com/redgreat/esdatacheck:latest'
        container_name: esdatacheck
        hostname: esdatacheck
        restart: unless-stopped
        volumes:
            - ./config/:/app/config
            - ./logs/:/app/logs
        environment:
            DISABLE_IPV6: 'true'
            TZ: 'Asia/Shanghai'
            LANG: 'zh_CN.UTF-8'
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 8M
        mem_swappiness: 0
        oom_kill_disable: true
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
